services:
  nodejs:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/workspaces
      - node_modules_volume:/workspaces/node_modules
    ports:
      - 5173:5173
    tty: true
    platform: linux/x86_64
volumes:
  node_modules_volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/node_modules
      o: bind
